package org.modelo.eventos;

public enum TipoEvento {
    // Tus eventos existentes
    TANQUE_MOVIDO,
    BALA_DISPARADA,
    TANQUE_DESTRUIDO,
    BLOQUE_DESTRUIDO,
    POWERUP_SPAWN,
    BASE_DESTRUIDA,
    BLOQUE_ACERO_IMPACTADO,
    TANQUE_BLINDADO_IMPACTADO,
    GRANADA_RECOGIDA,
    ENTE_AGREGADO,
    NIVEL_CARGADO,
    MOSTRAR_MENU,
    MOSTRAR_PARTIDA,
    MOSTRAR_FIN_PARTIDA
}

