package org.modelo.eventos;

public enum TipoEvento {
    TANQUE_MOVIDO,
    BALA_DISPARADA,
    TANQUE_DESTRUIDO,
    BLOQUE_DESTRUIDO,
    POWERUP_SPAWN,
    BASE_DESTRUIDA,
    BLOQUE_ACERO_IMPACTADO,
    TANQUE_BLINDADO_IMPACTADO,
    GRANADA_RECOGIDA,
    ENTE_AGREGADO,
    NIVEL_CARGADO
}
