package org.modelo.eventos;

public enum TipoEvento {
    BALA_DISPARADA,
    TANQUE_DESTRUIDO,
    BLOQUE_DESTRUIDO,
    BASE_DESTRUIDA,
    BLOQUE_ACERO_IMPACTADO,
    TANQUE_BLINDADO_IMPACTADO,
    GRANADA_RECOGIDA,
    NIVEL_CARGADO,
    MOSTRAR_MENU,
    MOSTRAR_PARTIDA,
    MOSTRAR_FIN_PARTIDA,
    CASCO_RECOGIDO,
    EFECTO_CASCO_TERMINADO
}

