package juego.eventos;

public enum TipoEvento {
    TANQUE_MOVIDO,
    BALA_DISPARADA,
    TANQUE_GOLPEADO,
    TANQUE_DESTRUIDO,
    POWERUP_GENERADO,
    POWERUP_RECIBIDO,
    NIVEL_COMPLETADO,
    JUEGO_TERMINADO,
    BLOQUE_DESTRUIDO,
    POWERUP_SPAWN, BASE_DESTRUIDA, BLOQUE_IMPACTADO, BLOQUE_ACERO_IMPACTADO, TANQUE_BLINDADO_IMPACTADO,
}
